version: "2"

volumes:
  postgres:

services:
  recorder:
    build:
      context: ./recorder
    volumes:
      - ./recorder:/usr/src/app
    env_file:
      - .env

  migrator:
    build:
      context: ./migrator
    volumes:
      - ./migrator:/usr/src/app
    env_file:
      - .env

  postgres:
    image: postgres:9.6.8-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
