version: "2"

volumes:
  postgres:
  redis:

services:
  listener:
    build:
      context: ./consumer
    command: listen
    volumes:
      - ./consumer:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis

  moment_purchased_fetcher:
    build:
      context: ./consumer
    command:
      - fetch
      - Market.MomentPurchased
    volumes:
      - ./consumer:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  moment_listed_fetcher:
    build:
      context: ./consumer
    command:
      - fetch
      - Market.MomentListed
    volumes:
      - ./consumer:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  moment_withdrawn_fetcher:
    build:
      context: ./consumer
    command:
      - fetch
      - Market.MomentWithdrawn
    volumes:
      - ./consumer:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  moment_price_changed_fetcher:
    build:
      context: ./consumer
    command:
      - fetch
      - Market.MomentPriceChanged
    volumes:
      - ./consumer:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  recorder:
    build:
      context: ./consumer
    command: record
    volumes:
      - ./consumer:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  migrator:
    build:
      context: ./migrator
    command: migrate
    volumes:
      - ./migrator:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6.8-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0.2-alpine
    ports:
      - 5434:6379
    command:
      - redis-server
      - --appendonly
      - "yes"
    volumes:
      - redis:/data
