name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_consumer:
    name: Deploy consumer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        run: docker build ./consumer --tag topshothawk-default/consumer

      - name: Tag image
        run: |
          docker tag topshothawk-default/consumer \
            ${{ steps.login-ecr.outputs.registry }}/topshothawk-default/consumer

      - name: Push image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/topshothawk-default/consumer

      - name: Force ECS deployment
        run: |
          for service in \
            listener \
            recorder \
            moment-purchased-fetcher \
            moment-listed-fetcher \
            moment-withdrawn-fetcher \
            moment-price_changed-fetcher
          do
            aws ecs update-service \
              --force-new-deployment \
              --service $service \
              --cluster topshothawk-default-nexus
          done

  deploy_migrator:
    name: Deploy migrator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        run: docker build ./migrator --tag topshothawk-default/migrator

      - name: Tag image
        run: |
          docker tag topshothawk-default/migrator \
            ${{ steps.login-ecr.outputs.registry }}/topshothawk-default/migrator

      - name: Push image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/topshothawk-default/migrator
